=== ログイン

ログイン処理を実装します。 +
コントローラに直接実装しても良いのですが、セッション操作系の処理は他のコントローラからも使用したいので、SessionHelper(ヘルパクラス)へ実装します。 +
MVC的にコントローラから他のコントローラへアクセスするような、同一レイヤー間でのやりとりするは好ましくないのです。

他のコントローラからも使用できるようにするためにApplicationControllerへインクルード（Mix-in）します。 +
以下のように実装してください。

[source, ruby]
.app/controllers/application_controller.rb
----
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # <1>
  include SessionsHelper
end
----

<1> セッションヘルパをインクルードする

これでアプリケーション全体でSessionsHelperを使用できるようになりました。

ログイン処理を行うlog_inメソッドを実装します。 +
ログイン処理ではセッションへユーザIDを保存します。
セッションへ値を保存するにはsessionメソッドを使用します。 +
以下のように実装してください。

[source, ruby]
.app/helpers/sessions_helper.rb
----
module SessionsHelper
  def log_in(user)
    # <1>
    session[:user_id] = user.id
  end
end
----

<1> セッションへユーザIDを格納する

実装したlog_inメソッドをログイン画面のcreateアクションで呼び出すようにしましょう。(TODOとしていた箇所を置き換えます) +
以下のように実装してください。

[source, ruby]
.app/controllers/sessions_controller.rb
----
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # <1>
      log_in(user)

      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
end
----

<1> ログイン処理を追加

これでログイン出来るようになりました。 +
ついでに、ユーザ登録した際に改めてログインするのが面倒なので、登録ユーザでログインするようにしてしまいましょう。 +
以下のように実装してください。

[source, ruby]
.app/controllers/users_controller.rb
----
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      # <1>
      log_in(@user)

      flash[:success] = "Welcome to the World!"
      redirect_to @user
    else
      render 'new'
    end
  end
end
----

<1> ユーザ登録成功時にログインを行う
