[suppress='InvalidSymbol']
=== ルーティング

Webブラウザで
link:http://localhost:3000/static_pages/home[http://localhost:3000/static_pages/home]
へアクセスするとホーム画面が表示されます。 +
これは '/static_pages/home' というパスへアクセスするとStaticPagesコントローラのhomeアクションが呼び出されるためです。 +
このパスとアクションの紐付け(ルーティング)は 'config/routing.rb' で実装されています。

[source, ruby]
.config/routes.rb
----
Rails.application.routes.draw do
  get 'static_pages/home'
end
----

ここで呼び出しているgetメソッドにより、 'static_pages/home' とStaticPagesコントローラのhomeアクションを紐づけています。 +
上記は紐づける先のアクションを指定するtoオプションが省略されているので判りにくいのですが、省略せずに書くと`get 'static_pages/home', to:'static_pages#home'`のようになります。 +
toオプションの表記は `<コントローラ名>#<アクション名>` です。
getメソッドではtoオプションを省略すると、指定されたパスから `<コントローラ名>/<アクション名>` のように判定するのですね。 +
ルーティングの実装に使用するメソッドはgetメソッドだけではなく、postメソッドやdeleteメソッドなどのhttpメソッドに対応したものに加えて、crud操作を行う時に必要になるルーティングを一括で実装するresourcesメソッドやルート（ '/' ）とアクションの紐付けに使用するrootメソッドなどの便利なメソッドも用意されています。

resourcesメソッドのような複数のルーティングを一括で実装するようなメソッドを使用したり、大量のルーティングを実装したりした場合、 'routes.rb' の記述を読んでルーティングを判断するのはなかなか大変になってきます。

RoRには 'routes.rb' が実装するルーティングを表示する 'rails routes' コマンドという便利なコマンドがあります。使ってみましょう。

[source, console]
.ルーティング確認
----
$ rails routes
           Prefix Verb URI Pattern                  Controller#Action
static_pages_home GET  /static_pages/home(.:format) static_pages#home
----

'routes.rb' を実際に実行してパスを生成しているので、少し時間がかかりますが、正確なルーティングが判るのでとても便利です。

さて、home画面はアプリケーションの初めの画面なので、表示するパスは 'static_pages/home' ではなく、ルートパスで表示したいです。 +
そこで、ルーティングを変更し、ルートパスでhome画面が表示されるようにしてみましょう。

==== 実装

ルートパスのGETにアクションを紐づける場合、getメソドでも実装できますが、rootメソッドというルートパスへの紐付け専用に用意されたメソッドがあるのでこれを使って実装してみましょう。
`root <アクションの指定>` のように使用します。

[source, ruby]
.config/routes.rb
----
Rails.application.routes.draw do
  root 'static_pages#home'
end
----

`rails routs` コマンドで確認してみましょう。

[source, console]
----
$ rails routes
Prefix Verb URI Pattern Controller#Action
  root GET  /           static_pages#home
----

ばっちりStaticPagesコントローラのhomeアクションがルートパスに設定されていますね。
link:http://localhost:3000[http://localhost:3000]でホーム画面が表示されるようになりました。

==== テスト

ルーティングを変更したので、Home画面表示のテストで使用していたURLパス取得用のヘルパメソッドであるstatic_pages_home_urlメソッドが生成されなくなりました。
テストを実行して見ると失敗ではなくエラーが出てしまいます。 +
そこで、テストのURLパス取得用ヘルパメソッドをルートパスのURLパス取得するroot_pathに置き換えましょう。

[source, ruby]
----
require 'test_helper'

class StaticPagesControllerTest < ActionDispatch::IntegrationTest
  test "should get home" do
    get root_path
    assert_response :success
    assert_select "title", "Home | Ruby on Rails Example"
  end
end
----

修正したら、テストを実行して観ましょう。
バッチリテストが成功するようになりましたね。
