=== パスワード

ログイン機能を実装するので、パスワードによる認証機能をユーザモデルに実装する必要があります。

パスワードによる認証を実装する場合、DBにパスワードを平文で格納するということはしません。
大抵はパスワードから生成したハッシュをDBへ保存し、認証時に入力されたパスワードから生成したハッシュと比べることでパスワードの正しさを確認します。

==== has_secure_passwordによる実装

Railsにはハッシュ化したパスワードの保存とパスワードの確認を行う機能を実装するための手段が用意されています。
ActiveRecordの**has_secure_password**メソッドを使うことでモデルにパスワード機能をモデルに組み込むことができます。

[source, rb]
./app/models/user.rb
----
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password # <1>
end
----
<1> パスワード機能の追加

has_secure_passwordメソッドを使うことで、**password**フィールドと**password_confirm**フィールド、そして**authenticte**メソッドが追加されます。

passwordフィールドとpassword_confirmフィールドはDBに保存しないフィールドで、ここにパスワードを格納して保存を行うことでDBへハッシュ化したパスワードを保存します。

パスワードの認証を行うにはauthenticteメソッドを使用します。
authenticteメソッドへパスワードを渡すことで、渡したパスワードが保存時にpasswordフィールドとpassword_confirmフィールドに設定していたパスワードと同一かどうか判断できます。

次に、DBへハッシュ化したパスワードを保存するフィールドを追加します。
has_secure_passwordメソッドによりパスワード機能を実装した場合、ハッシュ化したパスワードのフィールド名は**password_digest**になります。

では、マイグレーションファイルを生成しましょう。

[source, console]
----
$ rails generate migration add_password_digest_to_users password_digest:string
Running via Spring preloader in process 18356
      invoke  active_record
      create    db/migrate/20170910092439_add_password_digest_to_users.rb
----

今回はフィールド追加だけなので、生成されたマイグレーションファイルを編集する必要はありません。

[source, rb]
.db/migrate/20170910092439_add_password_digest_to_users.rb
----
class AddPasswordDigestToUsers < ActiveRecord::Migration[5.1]
  def change
    add_column :users, :password_digest, :string
  end
end
----

このまま、マイグレーションを実行します。

[souce, console]
----
$ rails db:migration
----

次に、パスワードをハッシュ化するために必要となるgemを追加します。
has_secure_passwordメソッドによるパスワード機能実装ではパスワードをハッシュ化するのに**bcrypt**というgemを使用しますが、プロジェクト生成時には組み込まれていないので新たに追加する必要があります。

gemファイルへbcryptを追加してください。

[source, rb]
.Gemfile
----
gem 'bcrypt',         '3.1.11'
----

サーバ起動中の場合はサーバを再起動することでbcryptが組み込まれます。

[NOTE]
====
このチュートリアルでは端末にbcryptがインストール済みとしています。
端末にbcryptがインストールされていない場合はGemfile編集後、Gemfileのあるディレクトリで `bundle install` を実行する必要があります。
====

さて、この状態でテストを実行してみると以前実装したテストでエラーが出るようになっています。

----
$ rails test
----

これはユーザモデルのテストでのユーザ生成時にpasswordフィールドとpassword_confirmフィールドを指定していないためです。
ユーザ生成時にpasswordフィールドとpassword_confirmフィールドを設定するように修正することで
エラーを解決できます。

[source, rb]
----
require 'test_helper'

class UserTest < ActiveSupport::TestCase
  # test "the truth" do
  #   assert true
  # end
  def setup
    @user = User.new(name: 'Example User', email: 'user@example.com',
                     password: "foobar", password_confirmation: "foobar")
  end
end
----

テストを実行すると、エラーが消えています。

----
$ rails test
----

==== 動作確認

has_secure_passwordメソッドによりパスワード機能を実装したので、テストを実装する必要はありませんが、動作は確認しておきたいです。

Railsにはirbを通して実装したコードを動作させる機能があります。
これを使ってパスワード機能の動作確認をしてみましょう。

まずは `rails console` でirbを起動します。

[source, console]
----
$ rails console
Running via Spring preloader in process 2512
Loading development environment (Rails 5.1.3)
irb(main):001:0>
----

[NOTE]
====
ちなみに、 `rails console --sandbox` とオプションを指定することで、サンドボックスモードで起動することができます。

サンドボックスモードで起動した場合、irb終了時にDBがロールバックされ、irbで行なったDB変更が元に戻ります。
====

ではirb上でUserを作成してみましょう。

[source, console]
.ユーザ作成
----
irb(main):001:0> User.create(name:"Akihiro.D", email:"d-akihiro@outlook.com", password:"foobar", password_confirmation:"foobar")

   (0.1ms)  begin transaction
  User Exists (2.6ms)  SELECT  1 AS one FROM "users" WHERE LOWER("users"."email") = LOWER(?) LIMIT ?  [["email", "d-akihiro@outlook.com"], ["LIMIT", 1]]
  SQL (2.9ms)  INSERT INTO "users" ("name", "email", "created_at", "updated_at", "password_digest") VALUES (?, ?, ?, ?, ?)  [["name", "Akihiro.D"], ["email", "d-akihiro@outlook.com"], ["created_at", "2017-09-23 05:01:07.962416"], ["updated_at", "2017-09-23 05:01:07.962416"], ["password_digest", "$2a$10$8yox84/8DwnlJOq6WkYxYe2npW2hXsS9w9kfDGhvqrRe71RWjuemq"]]
   (15.0ms)  commit transaction
=> #<User id: 1, name: "Akihiro.D", email: "d-akihiro@outlook.com", created_at: "2017-09-23 05:01:07", updated_at: "2017-09-23 05:01:07", password_digest: "$2a$10$8yox84/8DwnlJOq6WkYxYe2npW2hXsS9w9kfDGhvqrR...">
----

User.allで全ユーザを取得すると、作成したユーザがいることがわかります。

[source, console]
.全ユーザ取得
----
irb(main):003:0> user = User.find_by(email:"d-akihiro@outlook.com")

  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "d-akihiro@outlook.com"], ["LIMIT", 1]]
=> #<User id: 1, name: "Akihiro.D", email: "d-akihiro@outlook.com", created_at: "2017-09-23 05:01:07", updated_at: "2017-09-23 05:01:07", password_digest: "$2a$10$8yox84/8DwnlJOq6WkYxYe2npW2hXsS9w9kfDGhvqrR...">
----

**findby**メソッドで先ほど作成したユーザを取得します。
ログイン処理をするとき、メールアドレスでユーザを特定するので、それに合わせてメールアドレスでユーザを検索します。
取得したユーザはuser変数に格納しておきます。

[source, console]
.ユーザ検索
----
irb(main):003:0> user = User.find_by(email:"d-akihiro@outlook.com")

  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "d-akihiro@outlook.com"], ["LIMIT", 1]]
=> #<User id: 1, name: "Akihiro.D", email: "d-akihiro@outlook.com", created_at: "2017-09-23 05:01:07", updated_at: "2017-09-23 05:01:07", password_digest: "$2a$10$8yox84/8DwnlJOq6WkYxYe2npW2hXsS9w9kfDGhvqrR...">
----

では、取得したユーザでパスワード認証を行なってみましょう。
authenticateメソッドでパスワード認証を行います。
まずは間違ったパスワードを入力してみます。

[source, console]
.パスワード認証（NG）
----
irb(main):004:0> user.authenticate("bagbagbag")
=> false
----

パスワード認証はNGを返してきました。
次は正しいパスワードを入力してみます。

[source, console]
.パスワード認証（OK）
----
irb(main):004:0> user.authenticate("foobar")
=> #<User id: 1, name: "Akihiro.D", email: "d-akihiro@outlook.com", created_at: "2017-09-23 05:01:07", updated_at: "2017-09-23 05:01:07", password_digest: "$2a$10$8yox84/8DwnlJOq6WkYxYe2npW2hXsS9w9kfDGhvqrR...">
----

パスワード認証は成功しました。

[NOTE]
====
authenticateメソッドでは認証成功時にユーザ情報を返してきます。
もし、結果をtrue/falseで欲しい場合は、 `!!user.authenticate("foobar")` のようにすれば良いです。
====


==== バリデーション

パスワードを設定するとき、パスワードの強度は重要になってきます。
文字数や推測されにくい複雑さを保存時にシステム側でチェックするべきでしょう。
とりあえず、今回は文字数だけチェックするようにします。

最小文字列長を6文字とします。
また、空のパスワードというのもNGとしておきましょう。

まずはテストを実装します。

[source, rb]
----
require 'test_helper'

class UserTest < ActiveSupport::TestCase

  test 'password should be present (nonblank)' do # <1>
    @user.password = @user.password_confirmation = ' ' * 6
    assert_not @user.valid?
  end

  test 'password should have a minimum length' do # <2>
    @user.password = @user.password_confirmation = 'a' * 5
    assert_not @user.valid?
  end
end
----
<1>  空のパスワードのテストケース
<2> 短すぎるパスワード（5文字）のテストケース

テストは当然失敗します。

[source, console]
----
$ rails test
----

ユーザ名・パスワードと同じようにpasswordフィールへバリデーションを実装します。
（ちなみに、passwordと同じ文字列を入れないとバリデーションでNGとなるのでpassword_confirmationフィールドにはバリデーションを入れる必要はありません。）

[source, rb]
./app/models/user.rb
----

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password

  validates :password, presence: true, length: { minimum: 6 } # <1>
end
----
<1> passwordフィールドのバリデーション

テストを実行すると、passwordフィールドのバリデーションが正しく動作することが確認できます。

[source, console]
----
$ rails test
----
