=== Railsサーバ起動

作成したアプリケーションを動かしてみましょう。

まだ中身は空でデフォルトのページしかありませんが、動作させることが出来ます。

Railsでサーバを起動するには `rails server` コマンドを使用します。

[source, console]
.Railsサーバ起動
----
$ rails server --bind 0.0.0.0
----

ホストOSのWebブラウザでlink:http://localhost:3000[localhost:3000]へアクセスして見てください。
デフォルトのRailsページが表示されます。

[NOTE]
====
ホストOSでRuby on Railsのサーバを起動する場合は、 `--bind 0.0.0.0` オプションをつける必要はありません。
`rails server` だけで問題ありません。

`rails server` コマンドを実行すると、development(開発)環境としてサーバが起動します。

(ちなみに、production(本番)環境として起動する場合は、 `--environment` オプションで指定する必要があります。
未指定の場合development環境として起動します。)

Ruby on Railsのdevelopment環境ではデフォルトでサーバにループバックアドレスが割り当てられます。

同一ネットワーク上に公開されるのを防ぐために、このような動作をデフォルトとしているのです。

セキュリティ的には正しいのですが、仮想マシン上で開発を行おうとするとサーバがゲストOSのループバックアドレスへ割り当てられるので、ホストOSからサーバへアクセス出来なくなります。

そのため、 `--bind` オプションでサーバを `0.0.0.0` へ割り当てるように指定することで、外からアクセスできるようにしています。

以前はデフォルトで `0.0.0.0` へ割り当てられていましたが、Ruby on Rails 4.2でdevelopment環境ではデフォルトがループバックアドレスに変更されたらしいです。

link:http://guides.rubyonrails.org/4_2_release_notes.html#default-host-for-rails-server[http://guides.rubyonrails.org/4_2_release_notes.html#default-host-for-rails-server]

====
